const truths = [
"Apa rahasia terbesarmu yang belum pernah kamu ceritakan ke siapa pun?",
"Siapa orang yang paling sering kamu stalk di media sosial?",
"Pernah suka sama teman sendiri? Siapa?",
"Hal paling malu yang pernah kamu lakukan di sekolah?",
"Siapa gebetan pertamamu?",
"Pernah bohong ke orang tua? Tentang apa?",
"Apa kebiasaan aneh yang kamu punya?",
"Siapa orang yang kamu anggap paling keren di kelas?",
"Pernah ngirim chat ke orang yang salah? Ceritain dong!",
"Apa mimpi teraneh yang pernah kamu alami?",
"Siapa teman yang paling sering bikin kamu kesel?",
"Pernah nyontek pas ujian? Gimana caranya?",
"Siapa teman yang paling kamu percaya?",
"Pernah suka sama guru sendiri?",
"Apa ketakutan terbesarmu?",
"Pernah ketahuan bohong sama temen? Ceritain!",
"Apa username sosmed paling cringe yang pernah kamu pakai?",
"Siapa yang paling kamu kangenin saat ini?",
"Pernah nangis gara-gara film? Film apa?",
"Apa kebiasaan unik keluargamu di rumah?",
"Pernah suka sama pacar temen sendiri?",
"Apa hal paling random yang pernah kamu lakukan?",
"Siapa orang yang pernah bikin kamu baper banget?",
"Kalau bisa jadi siapa aja sehari, mau jadi siapa?",
"Pernah mimpi buruk sampai ketakutan sendiri?",
"Apa makanan terenak menurutmu tapi nggak banyak orang suka?",
"Pernah dighosting? Sama siapa?",
"Siapa teman lawan jenis yang paling dekat sama kamu?",
"Apa lagu yang sering kamu dengerin waktu galau?",
"Apa penyesalan terbesar dalam hidupmu?",
"Pernah ketahuan suka sama seseorang?",
"Siapa seleb yang paling kamu suka?",
"Apa hal paling aneh di HP-mu sekarang?",
"Pernah stalking mantan?",
"Apa chat terakhir di WhatsApp?",
"Siapa orang yang selalu bikin kamu ketawa?",
"Apa kebiasaan paling ngeselin temenmu?",
"Pernah ketiduran pas lagi chat sama siapa?",
"Apa nickname panggilan yang paling kamu suka?",
"Apa jurusan/kerja impianmu di masa depan?",
"Pernah ngaku-ngaku sakit biar nggak sekolah?",
"Apa meme favoritmu?",
"Kalau bisa pergi ke mana aja sekarang, mau ke mana?",
"Siapa yang terakhir kali kamu chat?",
"Pernah pura-pura ngerti padahal nggak?",
"Apa hal paling random yang pernah ada di history browser-mu?",
"Pernah suka sama dua orang sekaligus?",
"Apa skill tersembunyi yang orang lain nggak tahu?",
"Apa hal paling konyol yang pernah kamu percayai waktu kecil?",
"Siapa teman yang paling kamu rindukan sekarang?",
"Pernah ngupil di depan orang tanpa sadar?",
"Pernah ngaca sambil ngomong sendirian?",
"Siapa yang paling lo benci tapi harus pura-pura baik?",
"Pernah ngintip chat seseorang diam-diam?",
"Pernah nge-prank serius temen sampai panik?",
"Apa rahasia paling memalukan di kamar mandi?",
"Siapa crush yang paling absurd?",
"Pernah ngomong “aku sayang kamu” tapi bohong?",
"Pernah pura-pura sakit biar nggak sekolah?",
"Hal teraneh yang pernah lo mimpiin?",
"Pernah nyolong makanan orang lain diam-diam?",
"Siapa teman yang paling ngeselin tapi lo nggak bisa omong?",
"Pernah ketahuan nonton hal yang nggak boleh sama ortu?",
"Pernah nge-judge orang dari pakaian?",
"Hal memalukan apa yang paling sering terjadi sama lo?",
"Siapa guru favorit yang paling nggak mungkin lo suka?",
"Pernah salah kirim chat ke orang yang salah?",
"Pernah pura-pura ngerti materi tapi nggak ngerti sama sekali?",
"Pernah bikin drama buat perhatian temen?",
"Pernah jatuh cinta sama orang yang nggak mungkin?",
"Apa hal paling absurd yang bikin lo nangis?",
"Pernah makan makanan aneh tapi bohong bilang enak?",
"Siapa yang lo sering gosipin tapi nggak bilang ke dia?",
"Pernah pura-pura tidur biar nggak diganggu?",
"Pernah ketahuan bohong sama temen dekat?",
"Siapa orang paling ngeselin di sekolah?",
"Pernah pura-pura pinter biar nggak dicap bodoh?",
"Pernah gagal total waktu flirting?",
"Siapa yang bikin lo malu di depan umum?",
"Hal memalukan apa yang pernah direkam?",
"Pernah nggak sengaja nge-tag orang salah di medsos?",
"Pernah pura-pura setuju tapi nggak?",
"Siapa crush yang bikin lo nggak tidur semalaman?",
"Pernah salah paham sama temen karena chat?",
"Pernah ngelakuin hal aneh di kelas biar ketawa?",
"Siapa teman yang lo pengen prank banget tapi takut?",
"Pernah ketahuan baca diary orang lain?",
"Hal konyol apa yang lo lakukan buat hadiah?",
"Pernah bilang “gak apa-apa” padahal marah banget?",
"Siapa orang yang lo stalk tapi nggak diakuin?",
"Pernah pura-pura ngerti bahasa asing?",
"Pernah makan snack jatuh tapi tetep dimakan?",
"Siapa yang bikin lo kesal tapi nggak bisa diomongin?",
"Hal memalukan apa yang lo lakuin di publik?",
"Pernah ketahuan bohong soal umur atau tinggi badan?",
"Pernah salah paham sama guru?",
"Siapa teman yang bikin lo pengen kabur dari kelas?",
"Pernah pura-pura senyum padahal kesel banget?",
"Hal paling absurd yang bikin lo ketawa sendiri?",
"Pernah nyanyiin lagu konyol sendirian?"
];

const dares = [
"Upload foto jelekmu ke story selama 5 menit!",
"Coba ngomong pakai bahasa planet selama 1 menit.",
"Chat mantan dengan salam random.",
"Tiru suara hewan pilihan teman.",
"Ganti nama kontak teman jadi 'Crush' selama sehari.",
"Telepon orang tua dan bilang 'Aku kangen'.",
"Bikin video TikTok joget viral sekarang juga!",
"Bicara tanpa huruf 'a' selama 1 menit.",
"Baca chat terakhir di WhatsApp dengan suara keras.",
"Selfie dengan ekspresi paling aneh dan kirim ke grup.",
"Ucapkan 'Aku suka kamu' ke orang random di chat.",
"Jadi admin grup selama sehari.",
"Buat pantun spontan tentang salah satu teman.",
"Ceritakan mimpi teraneh yang pernah kamu alami.",
"Tiru gaya jalan seleb favoritmu.",
"Update status WA 'Aku lagi baper banget'.",
"Minta pulsa ke teman lewat chat.",
"Nyanyikan lagu favoritmu sekarang.",
"Ganti foto profil jadi foto kartun selama 1 hari.",
"Bikin story fake cry 10 detik.",
"Bicara dengan emoticon aja selama 10 menit.",
"Tulis puisi tentang makanan favoritmu.",
"Kasih compliment ke 3 teman di chat.",
"Ceritain pengalaman paling memalukan di sekolah.",
"DM selebgram dan bilang 'semangat ya kak!'",
"Jadi background Zoom/Google Meet paling absurd.",
"Bicara dengan logat daerah selama 2 menit.",
"Selfie dengan benda warna ungu dan upload.",
"Bikin video tutorial random (misal: cara makan kerupuk).",
"Jadi MC dadakan di grup selama 15 menit.",
"Tulis status 'Aku suka kamu' tanpa konteks.",
"Ganti ringtone HP jadi suara sendiri.",
"Nyanyi lagu anak-anak dengan suara keras.",
"Chat orang random: 'Aku mimpiin kamu semalam'.",
"Ucapkan kata 'uwu' di setiap kalimat selama 5 menit.",
"Tiru gaya bicara guru favoritmu.",
"Story 'Aku lagi nyari jodoh, ada yang mau?'",
"Bikin caption IG random tanpa makna.",
"Tiru ekspresi emoji favoritmu.",
"Tulis surat cinta untuk makanan.",
"Pura-pura jadi YouTuber selama 1 menit.",
"Selfie dengan gaya duck face lalu upload.",
"Cerita horor random ke grup.",
"Tulis pantun gombal di chat teman.",
"Tiru suara alarm HP.",
"Ganti status WA jadi 'Ngantuk banget'.",
"Buat video lipsync lagu pilihan teman.",
"Tulis di grup: 'Ada yang kangen aku nggak?'",
"Cerita pengalaman lucu masa kecil.",
"Makan satu sendok saus sambal super pedas.",
"Joget aneh 1 menit di depan semua orang.",
"Telepon temen dan bilang “Aku baru aja liat hantu”.",
"Pura-pura jadi guru 2 menit di kelas.",
"Kirim chat “Aku cinta kamu” ke temen random.",
"Minum air putih tapi sambil tutup mata 1 menit.",
"Pura-pura kesurupan 30 detik.",
"Lari keliling halaman sekolah 1 kali.",
"Post meme konyol di story.",
"Buat video lipsync aneh 30 detik.",
"Nyanyi lagu random di depan kelas.",
"Pura-pura nangis 1 menit di depan orang.",
"Tulis nama orang crush di tangan dan tunjukin.",
"Gambar tato palsu di tangan.",
"Lakukan 10 push-up sambil bilang “Aku kuat!”.",
"Pura-pura jadi zombie 30 detik.",
"Main kucing-kucingan di lantai selama 1 menit.",
"Telepon orang tua dan bilang “Aku cinta kamu” tanpa konteks.",
"Pakai topi aneh 1 jam.",
"Pura-pura jualan di depan temen.",
"Makan es batu 2 biji.",
"Pura-pura main gitar dengan pensil.",
"Lakukan gerakan yoga konyol 1 menit.",
"Berjalan mundur di kelas 1 menit.",
"Tiru suara hewan 30 detik.",
"Pakai baju terbalik selama 1 jam.",
"Buat video TikTok random dan simpan.",
"Pura-pura terbang di tempat.",
"Tulis pesan aneh ke crush dan kirim.",
"Tahan napas 15 detik sambil jongkok.",
"Tiru gaya berjalan temen 1 menit.",
"Lakukan 10 squat sambil teriak nama temen.",
"Pura-pura selfie dengan barang random.",
"Nyanyi lagu nasional tapi dengan nada aneh.",
"Main “freeze” selama 30 detik.",
"Lakukan gerakan robot 1 menit.",
"Berjalan sambil menutup mata 5 langkah.",
"Buat suara efek film horor 30 detik.",
"Tulis pesan absurd di kertas dan tunjukin ke orang.",
"Tiru aksen lucu 30 detik.",
"Pakai kaos kaki di tangan 10 menit.",
"Pura-pura jadi superhero 1 menit.",
"Buat pose konyol 1 foto dan tunjukin.",
"Lakukan 10 jumping jacks sambil bilang nama temen.",
"Tiru gerakan TikTok populer tapi konyol.",
"Pura-pura jadi reporter 1 menit.",
"Berjalan sambil nyanyi lagu random.",
"Pakai sendok di hidung 10 detik.",
"Gambar wajah temen di kertas tapi abstrak.",
"Pura-pura jadi kucing 1 menit."
];

function randomFrom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

document.getElementById("truthBtn").onclick = function() {
  showOutput(randomFrom(truths));
};
document.getElementById("dareBtn").onclick = function() {
  showOutput(randomFrom(dares));
};

function showOutput(text) {
  const out = document.getElementById('output');
  out.style.opacity = 0;
  setTimeout(() => {
    out.innerHTML = text;
    out.style.opacity = 1;
  }, 300);
}
